"""
Pattern 1: Agent Card Discovery
Financial Analysis Specialist Agent

This agent publishes an Agent Card at /.well-known/agent.json
The coordinator discovers it automatically via the A2A protocol.
"""

from google.adk.agents import Agent
from google.adk.tools import tool


@tool
def lookup_stock_data(symbol: str) -> dict:
    """
    Look up current stock data for a given ticker symbol.

    Args:
        symbol: Stock ticker symbol (e.g. GOOGL, AAPL)

    Returns:
        dict with price, change, volume, and market cap
    """
    # In production this would call a real financial API
    mock_data = {
        "GOOGL": {"price": 175.42, "change": "+1.2%", "volume": "24.5M", "market_cap": "2.1T"},
        "AAPL": {"price": 189.30, "change": "-0.5%", "volume": "52.1M", "market_cap": "2.9T"},
        "MSFT": {"price": 415.20, "change": "+2.1%", "volume": "18.3M", "market_cap": "3.1T"},
    }
    return mock_data.get(symbol.upper(), {
        "price": 100.0,
        "change": "0.0%",
        "volume": "1M",
        "market_cap": "100B",
        "note": f"Mock data for {symbol}"
    })


@tool
def generate_financial_report(symbol: str, timeframe: str = "1M") -> str:
    """
    Generate a financial analysis report for a stock.

    Args:
        symbol: Stock ticker symbol
        timeframe: Analysis period — 1W, 1M, 3M, 1Y

    Returns:
        Formatted financial report as a string
    """
    timeframe_labels = {"1W": "1 week", "1M": "1 month", "3M": "3 months", "1Y": "1 year"}
    label = timeframe_labels.get(timeframe, timeframe)

    return f"""
FINANCIAL ANALYSIS REPORT
Symbol: {symbol.upper()}
Timeframe: {label}
Generated by: Financial Analysis Agent (A2A)

Summary:
- Performance over {label}: Moderate growth with stable fundamentals
- Risk profile: Medium
- Analyst consensus: Buy
- Key metrics: P/E ratio 28.5, Revenue growth 12% YoY

Recommendation: Hold with potential upside of 8-12% over the next quarter.
    """.strip()


# The ADK agent — to_a2a() will auto-generate its Agent Card
financial_agent = Agent(
    name="financial_analysis_agent",
    model="gemini-2.0-flash",
    description=(
        "Specialist agent for financial analysis. "
        "Capabilities: stock data lookup, financial report generation. "
        "Auth: Service Token."
    ),
    instruction=(
        "You are a financial analysis specialist. "
        "Use your tools to look up stock data and generate reports. "
        "Always provide specific numbers and clear recommendations."
    ),
    tools=[lookup_stock_data, generate_financial_report],
)
